#!/usr/bin/env bash
# Concatenate docs/integrated/*.md into agent/AGENTS.md.
# Files are joined in lexical (filename) order — use numeric prefixes to control.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/docs/integrated"
OUT="$ROOT/agent/AGENTS.md"

if [[ ! -d "$SRC" ]]; then
  echo "[build] no source dir: $SRC" >&2
  exit 1
fi

shopt -s nullglob
files=("$SRC"/*.md)
shopt -u nullglob

if [[ ${#files[@]} -eq 0 ]]; then
  echo "[build] no source files in $SRC" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!--"
  echo "  AUTOGENERATED by build.sh from docs/integrated/*.md."
  echo "  Do not edit this file directly. Edit sources and re-run ./build.sh."
  echo "  Sources (in order):"
  for f in "${files[@]}"; do
    echo "    - docs/integrated/$(basename "$f")"
  done
  echo "-->"
  echo

  first=1
  for f in "${files[@]}"; do
    if [[ $first -eq 0 ]]; then echo; fi
    cat "$f"
    first=0
  done
} > "$tmp"

# Ensure trailing newline
[[ -z "$(tail -c1 "$tmp")" ]] || echo >> "$tmp"

mv "$tmp" "$OUT"
trap - EXIT
echo "[build] wrote $OUT (${#files[@]} source file(s))"
