#!/usr/bin/env bash
# Claude Code PostToolUse hook (matcher: Edit|Write|MultiEdit|NotebookEdit).
# Accumulates a per-session count of *substantive* changed lines so the Stop hook
# (verify-standards.sh) fires the self-review only after meaningful logic changes —
# not on every cosmetic tweak. "Substantive" excludes blank lines, comment-only
# lines, and punctuation-only lines (closing braces, lone parens, etc.). Counting
# old-vs-new intent (not the on-disk file) also means ruff's auto-format churn
# never inflates the count.

input="$(cat)"

path="$(printf '%s' "$input" | jq -r '
  .tool_input.file_path // .tool_input.path // .tool_input.notebook_path // empty
' 2>/dev/null)"
[[ -z "$path" ]] && exit 0

case "$path" in
  *.py|*.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.go|*.rs|*.java|*.kt|*.rb|*.php|*.cs|\
  *.swift|*.c|*.h|*.cc|*.cpp|*.hpp|*.sh|*.bash|*.sql) ;;
  *) exit 0 ;;
esac
# Standards docs, generated context, and autogenerated migrations are not
# "core logic under review".
case "$path" in
  */docs/standards/*|*AGENTS.md|*CLAUDE.md) exit 0 ;;
  */alembic/versions/*|*/migrations/versions/*) exit 0 ;;
esac

# old / new text for this edit. Handles Edit (old/new_string), Write (content),
# NotebookEdit (new_source), and MultiEdit (edits[].{old,new}_string joined).
old="$(printf '%s' "$input" | jq -r '
  if .tool_input.old_string != null then .tool_input.old_string
  elif (.tool_input.edits | type) == "array" then (.tool_input.edits | map(.old_string) | join("\n"))
  else "" end
' 2>/dev/null)"
new="$(printf '%s' "$input" | jq -r '
  if .tool_input.new_string != null then .tool_input.new_string
  elif .tool_input.content != null then .tool_input.content
  elif .tool_input.new_source != null then .tool_input.new_source
  elif (.tool_input.edits | type) == "array" then (.tool_input.edits | map(.new_string) | join("\n"))
  else "" end
' 2>/dev/null)"

# Drop blank / comment-only / punctuation-only lines so cosmetic churn scores 0.
strip_trivial() {
  grep -vE '^[[:space:]]*$' \
    | grep -vE '^[[:space:]]*(#|//|--|\*|/\*)' \
    | grep -vE '^[[:space:]]*[(){}\[\];,:]+[[:space:]]*$'
}

added="$(diff <(printf '%s' "$old") <(printf '%s' "$new") \
  | sed -n 's/^> //p' | strip_trivial | wc -l | tr -d ' ')"
removed="$(diff <(printf '%s' "$old") <(printf '%s' "$new") \
  | sed -n 's/^< //p' | strip_trivial | wc -l | tr -d ' ')"

# Net substantive change for this edit = the larger of added / removed lines
# (avoids double-counting a pure replacement).
changed=$(( added > removed ? added : removed ))
[[ "$changed" -eq 0 ]] && exit 0

session="$(printf '%s' "$input" | jq -r '.session_id // "default"' 2>/dev/null)"
marker="$HOME/.claude/.standards-review-pending-${session}"
prev=0
[[ -f "$marker" ]] && prev="$(cat "$marker" 2>/dev/null)"
[[ "$prev" =~ ^[0-9]+$ ]] || prev=0
printf '%s' "$(( prev + changed ))" > "$marker"
exit 0
